### ISSUE TITLE
TODO List

### ISSUE THREAD

**Issue by gabrielbdornas** [gabrielbdornas/check-phone-numbers#1]
- Gols:
  - Check [Cadastrofone](https://cadastropre.com.br/ ) website every day;
  - Look for numbers stored in env vars:
    -  CHECK_NAME: CPF, [CELPHONE_NUMBERS]
  - If numbers different from the env vars list send an email; and
  - If numbers not different from the env vars list do nothing;

- [ ] Remove REAMDE.md content;
- [ ] Criate virtual env with;
- [ ] Include selenium and dotenv on `requirements.txt` file;
- [ ] Install packages;
- [ ] Create .env file, fill vars and check with `echo` statament if it's working;
- [ ] Create a method class to search numbers;
- [ ] Create a method class to compare env var numbers with searced numbers; and
- [ ] Create a method class to send mail if necessary.
